# Generated by Django 6.0.5 on 2026-05-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_people', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Trống'), ('OCCUPIED', 'Đã thuê'), ('MAINTENANCE', 'Bảo trì')], default='AVAILABLE', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
        ),
    ]
