# Generated by Django 6.0.5 on 2026-05-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('room_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('electric_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('water_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán'), ('OVERDUE', 'Quá hạn')], default='UNPAID', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('old_electric', models.PositiveIntegerField()),
                ('new_electric', models.PositiveIntegerField()),
                ('old_water', models.PositiveIntegerField()),
                ('new_water', models.PositiveIntegerField()),
                ('electric_price', models.DecimalField(decimal_places=2, default=3500, max_digits=10)),
                ('water_price', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='contracts.contract')),
            ],
        ),
    ]
